version: '1.0'

jobs:

  runs-on: node-ci-base:latest

  setup:
    steps:
      - name: Clean Workspace
        run: rm -rf /workspace/app

      - name: Clone repo
        run: git clone https://github.com/Sectani/Node-App /workspace/app

      - name: Install dependencies
        working-directory: /workspace/app/
        run: npm ci

  test:
    depends-on: setup
    steps:
      - name: Run tests
        working-directory: /workspace/app/
        run: npm test

  build:
    depends-on: test
    steps:
      - name: Build
        working-directory: /workspace/app/
        run: npm run build || echo "No build script defined"

      - name: Copy artifacts
        run: cp -r build /artifacts/ || echo "No build found"

  deploy:
    depends-on: build
    steps:
      - name: Build Docker Image
        working-directory: /workspace/app/
        run: docker build -t sectani/node-app:latest .

      - name: Login to Docker Hub
        run: |
          echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_EAMIL" --password-stdin

      - name: Push Docker Image
        run: docker push sectani/node-app:latest

      - name: Deploy to Kubernetes
        working-directory: .
        run: |
          cat <<EOF > /tmp/kubeconfig
          apiVersion: v1
          clusters:
          - cluster:
              certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTkRrNE9UYzFPRFl3SGhjTk1qVXdOakUwTVRBek9UUTJXaGNOTXpVd05qRXlNVEF6T1RRMgpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTkRrNE9UYzFPRFl3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTK2c5ZjYxd2czVCs3MlNSejJPdjBrOW9iQ2F0d2llU3p5T2NuYWlYdGIKc1VTY2s2R1ArMm8rVjVraVFiVFBLVWNQTWRRZDJIRHk4QjRuSWNQaDZaSnNvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWZaQnZ4Zm5xMkFaL0VHUUZzUHZnCndpLzBRMTR3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQUlVNXhZVFV5bHBnVGtpcVI0RjZBRmFVTGhJeVcxcXAKUGZvczJvbVB3UUZ5QWlBdDFnMUx6TTBhZmd6ZVBMd2ZuTTNSYk4wMjM0QzhRMmF1bWtYYU0zNGJTdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
              server: https://host.docker.internal:6443
            name: k3d-mycluster
          contexts:
          - context:
              cluster: k3d-mycluster
              user: admin@k3d-mycluster
            name: k3d-mycluster
          current-context: k3d-mycluster
          kind: Config
          preferences: {}
          users:
          - name: admin@k3d-mycluster
            user:
              client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJSS9LbndqQXd5Z0F3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOelE1T0RrM05UZzJNQjRYRFRJMU1EWXhOREV3TXprME5sb1hEVEkyTURZeApOREV3TXprME5sb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJMbFRudElCMUpxOUIrVEkKSWRVYitxdkxDeWhMTFBFcmJybGpCSjV2b3QrbzNwVTlCaUp6NWZVd2lFSVBVcDJuMGlUSGNFT3RMRXN0RzFtWQpZR0ttWVVHalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUytEcUlpZFYyUklncEE0aXBMdDhTNnZmaXZyekFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlFQTFndmxXKzZ6SlBTM2w1emRBV3J0eDA2SWJ6VSt4SWRucWZENnFseDRXL01DSUZMellDWlBva2lZZmlBZQpsc1pWYXlUb0VqRDJETXl4eUtUWll6WC9SR1JHCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzTkRrNE9UYzFPRFl3SGhjTk1qVXdOakUwTVRBek9UUTJXaGNOTXpVd05qRXlNVEF6T1RRMgpXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzTkRrNE9UYzFPRFl3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTN0lxTjFONW1KZzZQRVg2bzNkbUI3U0pDVVRtSzZ5ZHhLS2ZoMU9mbHoKRVFBc0ZTU0s4NWdQRnBDOEJsb3lMMkIyTE00RHlPenhGUU5MT08rSUlZUHlvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXZnNmlJblZka1NJS1FPSXFTN2ZFCnVyMzRyNjh3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQUl5WGNuNlJKUmRZWUJTTXcxamlSSmZYK1dEV3JMem8KWklyLy9CYjZGRHVoQWlCZytjUDB2ZEdYM3lGNEpJSGVad2JEKzJxUlF0N3Y3OTdGdlplQWZteXYvdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
              client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUxoQnJvSVVUb0VJZEZveTJGMXpyMHk5clVxRmFTYlJMb0dXM0ZBeEtrVnVvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFdVZPZTBnSFVtcjBINU1naDFSdjZxOHNMS0VzczhTdHV1V01Fbm0raTM2amVsVDBHSW5QbAo5VENJUWc5U25hZlNKTWR3UTYwc1N5MGJXWmhnWXFaaFFRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
          EOF
          export KUBECONFIG=/tmp/kubeconfig
          kubectl apply -f deployment.yml
          kubectl rollout status deployment/node-app
